### ISSUE TITLE
Comment of Appreciation

### ISSUE THREAD

**Issue by Awbmilne** [oswida/joplin-markdown-calc#1]
And before you know it... Im using Joplin for all my Excel tasks.

Really appreciate this! Great Idea! Hope it can get pulled into Joplin.

**Comment by shantanugoel** [comment]
Piggy backing on this comment. @oswida do you plan to complete this plugin? I'd love to use it.

**Comment by oswida** [comment]
Yes, I will finish it.  This plugin is still on the working queue :), but I'll try to move it few places ahead :) .

**Comment by oswida** [comment]
Finished.
