### ISSUE TITLE
Cells containing strings that start with digits are treated as numbers

### ISSUE THREAD

**Issue by deftdawg** [oswida/joplin-markdown-calc#18]
**EDIT:** search for "beers" example in follow up comments below, this issue is more widespread than just dates.

Any chance that we can have quotes added when they are missing?   Feels kind of silly putting quotes around date values in a column. 

| Week | Date ||
|:---------|:------|:------|
|\<!--FM WEEKNUM(B1)--\> 3|"2022-01-10"|Ok|
|\<!--FM WEEKNUM(B2)--\> 28|2022-01-10| <-- Shouldn't be week 28|
|\<!--FM WEEKNUM(B3)--\> 24|"2022-06-07"|Ok|

**Comment by oswida** [comment]
We need to make some kind of assumption here. For the typing purposes, parser tries to find out if the cell value is a number. Unfortunately, `Number.parse` works correctly with the strings like '2022-01-10', so this is why it is parsed unproperly. 
To satisfy the requirement I need to recognize if a given string is a date or a number, maybe I can find some library for that, but still dates will have to be put in a proper format anyway. 
Unfortunately again, `Date.parse(1984)` gives a proper result too.

**Comment by deftdawg** [comment]
Can we assume something like a trimmed value matching something like `^-? \n+(\.\n+)?` is a number and everything else is a string?  Maybe it would be easier

**Comment by oswida** [comment]
There are multiple formats for a number, what about locale dependent or scientific notation?

**Comment by oswida** [comment]
If you look into the code, you certainly find out that I've implemented `isNan` check for `Numbar.parseFloat` long time ago. 
And no, `parseFloat` is not returning `isNan` for `2022-01-10` (even if you put it as a string argument).

**Comment by deftdawg** [comment]
Meh, even if I figure out how to fix this number handling bug, it looks like my dream of using this for time calculations is toasted because the difference between how DATEVALUE as it is done with formula JS and how it's handled by this plugin.

| Source | Method | Value | Note |
|:---------|:------|:----|:----|
|Markdown Calc|\| 40778| This is an Excel Date (Days since Jan 1 1900) - Time info is lost 😢 |
|[Formula JS](https://formulajs.info/functions/)|DATEVALUE('8/22/2011') * 1 |1313985600000| /1000 = Unix epoch time i.e. gdate -d @1313985600 = Mon Aug 22 00:00:00 EDT 2011|
 
This formula works in Formula JS, but it's hopeless without time data... 
```
((DATEVALUE(REGEXREPLACE(DATEVALUE("2022-09-07")+"","\\d\\d:\\d\\d:\\d\\d","5:30 PM")) - DATEVALUE(REGEXREPLACE(DATEVALUE("2022-09-07")+"","\\d\\d:\\d\\d:\\d\\d","8:00 AM")))/3600000)
```
(result is "9.5" hours)

**Comment by oswida** [comment]
I do not see any reasonable way to fulfill such a requirement.
