### ISSUE TITLE
Floating point math issue

### ISSUE THREAD

**Issue by l33tllama** [oswida/joplin-markdown-calc#4]
Hi, thanks for the awesome plugin! Really useful for work hour tracking for example..

I have noticed an issue, not sure if with this plugin or Joplin, but it has some troubles with floating point additions. That old chestnut..

![Screen Shot 2021-03-23 at 5 05 15 pm](https://user-images.githubusercontent.com/3285878/112101100-3ad42a80-8bfa-11eb-9820-1e7459399256.png)

Edit: A possible solution: [https://www.thewebflash.com/solution-for-floating-point-problems-in-javascript/](https://www.thewebflash.com/solution-for-floating-point-problems-in-javascript/)

**Comment by oswida** [comment]
It is not possible to control the computing operations from the Joplin plugin level. All calculations are performed by https://github.com/handsontable/formula-parser

**Comment by l33tllama** [comment]
Thank you for the response. I understand that it's not something you can fix. I might submit an issue with the formula-parser repository.. :)
