### ISSUE TITLE
Text handling

### ISSUE THREAD

**Issue by sakr101** [oswida/joplin-markdown-calc#6]
does the plug-in support string handling ?
when trying to return a string value from cell it returns NaN:
| Column A | Column B | Column C |
|:---------|:---------|:---------|
|j           | 456     | 789     |
| 0        | 0        |NaN|

`<!--TBLFM C2=A1    -->`

**Comment by oswida** [comment]
No, cell values are converted to float numbers.

**Comment by iAnyKey** [comment]
I guess you mean this line: https://github.com/oswida/joplin-markdown-calc/blob/fae0e6dcc301cbe5deba8c77e97dd92ca42e81b3/src/lib/table.ts#L140
Would it be possible to add support of textvalue handling?
so we could use numerous [Date and Time functions](https://formulajs.info/functions/) of formulas.js like `HOUR('7/18/2011 7:45:00 AM')` returning `7`

**Comment by oswida** [comment]
Could you provide some examples of such use for testing. I will check if I can support string values.
